name: Build

on:
  push:
    # branches: [master]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs: 
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: Release ${{ github.ref }}
        draft: false
        allowUpdates: true

  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller -F -w -n sbte-formatter -i src/icon.icns src/main.py &&
                cd dist/ &&
                zip -r9 sbte-formatter sbte-formatter.app/
            OUT_FILE_NAME: sbte-formatter-macos.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n sbte-formatter -i src/favicon.ico src/main.py
            OUT_FILE_NAME: sbte-formatter.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}


    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: Release ${{ github.ref }}
        draft: false
        allowUpdates: true
        artifacts: ./dist/${{ matrix.OUT_FILE_NAME}}
        artifactContentType: ${{ matrix.ASSET_MIME}}

  finish:
    name: Finish Release
    runs-on: ubuntu-latest
    needs: [build, createrelease]
    steps:
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        allowUpdates: true
        # title: Release ${{ github.ref }}
        draft: false
        generateReleaseNotes: true